#!/usr/bin/env python3
"""Inject historical UI-test environment variables into an Xcode 26 xctestrun.

Xcode 26 does not reliably pass the parent shell environment to XCTest when
using generated projects. This script patches the plist in place without
storing any credential in the repository.
"""

from __future__ import annotations

import argparse
import os
import plistlib
from pathlib import Path


REQUIRED_KEYS = [
    "PXJ_UI_TEST_EMAIL",
    "PXJ_UI_TEST_PASSWORD",
    "PXJ_HISTORY_TEST_MARKER",
    "PXJ_HISTORY_SESSION_ID",
    "PXJ_HISTORY_MISTAKE_ID",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("xctestrun", help="Path to the .xctestrun plist generated by build-for-testing")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    path = Path(args.xctestrun)
    missing = [key for key in REQUIRED_KEYS if not os.environ.get(key)]
    if missing:
        raise SystemExit(f"missing required environment variables: {', '.join(missing)}")
    values = {key: os.environ[key] for key in REQUIRED_KEYS}
    with path.open("rb") as handle:
        payload = plistlib.load(handle)
    patched = 0
    for config in payload.get("TestConfigurations", []):
        for target in config.get("TestTargets", []):
            if not target.get("IsUITestBundle"):
                continue
            for env_key in ("EnvironmentVariables", "TestingEnvironmentVariables", "UITargetAppEnvironmentVariables"):
                target.setdefault(env_key, {}).update(values)
            patched += 1
    if patched == 0:
        raise SystemExit(f"no UI test targets found in {path}")
    with path.open("wb") as handle:
        plistlib.dump(payload, handle)
    print(f"patched {patched} UI test target(s) in {path}")


if __name__ == "__main__":
    main()
