"""Create image-level question detector candidates from a plain image folder."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from PIL import Image, ImageOps


IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}


def stable_id(value: str, length: int = 16) -> str:
    return hashlib.sha1(value.encode("utf-8")).hexdigest()[:length]


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")


def maybe_clean(path: Path, clean: bool) -> None:
    if clean and path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def image_size(path: Path) -> tuple[int, int] | None:
    try:
        with Image.open(path) as raw:
            image = ImageOps.exif_transpose(raw)
            return image.size
    except Exception:
        return None


def collect_images(root: Path, recursive: bool) -> list[Path]:
    iterator = root.rglob("*") if recursive else root.glob("*")
    return sorted(path for path in iterator if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES)


def build_candidates(args: argparse.Namespace) -> dict[str, Any]:
    source_dir = args.image_dir.resolve()
    if not source_dir.is_dir():
        raise SystemExit(f"image dir not found: {source_dir}")
    maybe_clean(args.out, args.clean)
    images_dir = args.out / "positive"
    images_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    skipped: dict[str, int] = {}
    for index, source in enumerate(collect_images(source_dir, args.recursive), start=1):
        size = image_size(source)
        if size is None:
            skipped["unreadable_image"] = skipped.get("unreadable_image", 0) + 1
            continue
        width, height = size
        image_id = stable_id(str(source.resolve()))
        target_name = f"{source.stem[:90]}_{image_id}{source.suffix.lower()}"
        target = images_dir / target_name
        shutil.copy2(source, target)
        rows.append(
            {
                "image": f"positive/{target_name}",
                "candidate_kind": "plain_image_dir_positive",
                "needs_box_label": True,
                "review_only": True,
                "image_id": image_id,
                "session_id": f"pimage_{index:05d}",
                "batch_id": "plain_image_dir",
                "source_path": str(source),
                "width": width,
                "height": height,
                "note": "Image-dir candidate; boxes are generated by prelabel/distillation and must pass quality gates before training use.",
            }
        )
        if args.limit and len(rows) >= args.limit:
            break

    write_jsonl(args.out / "positive_candidates.jsonl", rows)
    metadata = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_dir": str(source_dir),
        "candidate_count": len(rows),
        "skipped": skipped,
        "recursive": bool(args.recursive),
        "outputs": {"positive_manifest": "positive_candidates.jsonl", "images_dir": "positive"},
    }
    write_json(args.out / "metadata.json", metadata)
    return metadata


def main() -> None:
    parser = argparse.ArgumentParser(description="Create detector review candidates from a plain image directory.")
    parser.add_argument("image_dir", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--recursive", action="store_true")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--clean", action="store_true")
    args = parser.parse_args()
    report = build_candidates(args)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
